# https://github.com/marketplace/actions/labeler

kalix-proxy:
  - '**/*'

java-sdk:
  - sdk/java-sdk/**/*
  - sdk/java-sdk-testkit/**/*
  - maven-java/**/*
  - codegen/java-gen/**/*
  - samples/java-protobuf-*/**/*

scala-sdk:
  - sdk/scala-sdk/**/*
  - sdk/scala-sdk-testkit/**/*
  - sbt-plugin/**/*
  - codegen/scala-gen/**/*
  - samples/scala-protobuf-*/**/*


spring-sdk:
  - sdk/spring-sdk/**/*
  - sdk/spring-sdk-testkit/**/*
  - samples/java-spring-*/**/*

Documentation:
  - docs/**/*
