# https://github.com/marketplace/actions/labeler

kalix-proxy:
  - '**/*'

java-sdk:
  - sdk/java-sdk/**/*
  - sdk/java-sdk-testkit/**/*
  - maven-java/**/*
  - codegen/java-gen/**/*

scala-sdk:
  - sdk/scala-sdk/**/*
  - sdk/scala-sdk-testkit/**/*
  - sbt-plugin/**/*
  - codegen/scala-gen/**/*

spring-sdk:
  - sdk/spring-sdk/**/*

Documentation:
  - docs/**/*
