# https://github.com/marketplace/actions/labeler

kalix-proxy:
  - '**/*'

java-protobuf-sdk:
  - sdk/java-sdk/**/*
  - sdk/java-sdk-testkit/**/*
  - maven-java/**/*
  - codegen/java-gen/**/*
  - samples/java-*/**/*

scala-protobuf-sdk:
  - sdk/scala-sdk/**/*
  - sdk/scala-sdk-testkit/**/*
  - sbt-plugin/**/*
  - codegen/scala-gen/**/*
  - samples/scala-*/**/*


java-sdk:
  - sdk/spring-sdk/**/*
  - sdk/spring-sdk-testkit/**/*
  - sdk/java-sdk-spring/**/*
  - sdk/java-sdk-spring-testkit/**/*
  - samples/spring-*/**/*

Documentation:
  - docs/**/*
