version: "3"
services:
  # note the ports being different from other sample docker-compose files to allow this service to run
  # on the same local machine as the scala-customer-registry-
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.8
    ports:
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dconfig.resource=dev-mode.conf
        -Dlogback.configurationFile=logback-dev-mode.xml
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8081}
