version: "3"
services:
  # note the ports being different from other sample docker-compose files to allow this service to run
  # on the same local machine as the scala-protobuf-eventsourced-customer-registry
  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.1.24
    container_name: scala-protobuf-eventsourced-customer-registry-subscriber
    ports:
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: "8081"
