version: 2.1

jobs:
  checks:
    description: "Checks"
    docker:
      - image: circleci/openjdk:11
    steps:
      - run:
          command: echo "Dummy check as PR validation moved to the GH workflow"

workflows:
  CI:
    jobs:
      - checks
