version: 2.1

orbs:
  build-tools: circleci/build-tools@2.9.0
  github-cli: circleci/github-cli@1.0.2

commands:
  checkout-and-merge-to-main:
    steps:
      - checkout
      - run:
          name: Configure git user
          command: |
            # required by merge-with-parent (for some unknown reason)
            git config user.email "circleci@example.com"
            git config user.name "CircleCI"
      - build-tools/merge-with-parent:
          parent: main

  install-java:
    description: install openjdk-17
    steps:
      - run:
          name: Install java 17
          command: |
            wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4.1%2B1/OpenJDK17U-jdk_x64_linux_hotspot_17.0.4.1_1.tar.gz -O /tmp/openjdk-17.tar.gz

            sudo mkdir -p /usr/lib/jvm
            sudo tar xfvz /tmp/openjdk-17.tar.gz --directory /usr/lib/jvm
            rm -f /tmp/openjdk-17.tar.gz

            sudo sh -c 'for bin in /usr/lib/jvm/jdk-17.0.4.1+1/bin/*; do update-alternatives --install /usr/bin/$(basename $bin) $(basename $bin) $bin 100; done'
            sudo sh -c 'for bin in /usr/lib/jvm/jdk-17.0.4.1+1/bin/*; do update-alternatives --set $(basename $bin) $bin; done'

  setup_sbt:
    description: "Set up sbt"
    parameters:
      version:
        type: string
        default: "1.7.2"
    steps:
      - install-java
      - run:
          name: Install sbt
          command: |
            curl -L -o sbt-<< parameters.version >>.deb https://repo.scala-sbt.org/scalasbt/debian/sbt-<< parameters.version >>.deb
            sudo dpkg -i sbt-<< parameters.version >>.deb
            rm sbt-<< parameters.version >>.deb
      - restore_cache:
          # https://circleci.com/docs/caching#restoring-cache
          keys:
            # new cache if sbt version changed
            - sbt-cache-v3-{{ checksum "project/build.properties" }}-

  save_deps_cache:
    description: "Save sbt caches"
    steps:
      - save_cache:
          key: sbt-cache-v3-{{ checksum "project/build.properties" }}-
          paths:
            - "~/.sbt"
      - save_cache:
          key: sbt-dependencies-v1-{{ checksum "project/Dependencies.scala" }}-
          paths:
            - "~/.ivy2/cache"
            - "~/.cache/coursier"

  restore_deps_cache:
    description: "Restore sbt dependency cache"
    steps:
      - restore_cache:
          key: sbt-dependencies-v1-{{ checksum "project/Dependencies.scala" }}-

  set-sdk-version:
    description: "Set global option, grab current SDK version"
    steps:
      - run:
          name: "Set SDK version and global options"
          command: |
            echo "export VERSION_CHECK_ON_STARTUP=false" >> $BASH_ENV
            if [ -e workspace/published-version ]; then
              echo "Extracting version from previous publish step"
              echo 'export SDK_VERSION='`cat workspace/published-version` >> $BASH_ENV
            else
              # tail 2 + head 1 because CircleCI adds an extra line
              # the SDK_VERSION is later used to run the maven tests (see below)
              echo "Extracting version from sbt build"
              echo 'export SDK_VERSION='`sbt "print javaSdkProtobuf/version" | tail -n 2 | head -n 1` >> $BASH_ENV
            fi

  publish-local:
    description: Build and publish artifacts and plugins locally for other tests to use
    steps:
      - run:
          name: publish m2 and local
          command: sbt publishM2 publishLocal -Ddisable.apidocs=true
      - run:
          name: "Build maven-java"
          command: |
            cd maven-java
            echo "Running maven-java with SDK version: '$SDK_VERSION'"
            mvn versions:set -DnewVersion=$SDK_VERSION
            mvn verify install
      - run: mkdir -p workspace
      - run: cp -r ~/.m2 workspace/
      - run: cp -r ~/.ivy2 workspace/
      - run: echo $SDK_VERSION > workspace/published-version
      # copy published files to workspace for other jobs to pick up rather than build their own
      - persist_to_workspace:
          root: workspace
          paths:
            - .m2
            - .ivy2
            - published-version
  copy-from-workspace:
    description: Copy locally published artifacts from workspace
    steps:
      - attach_workspace:
          at: workspace
      - run: rsync -rv workspace/.m2/ ~/.m2/
      - run: rsync -rv workspace/.ivy2/ ~/.ivy2/

jobs:
  checks:
    docker:
      - image: cimg/openjdk:11.0
    description: "Checks"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
          name: Run scalafmt checks
          command: |
            sbt scalafmtCheckAll scalafmtSbtCheck || \
              { echo "[error] Code not formatted prior to commit. Run 'sbt scalafmtAll scalafmtSbt' then commit the reformatted code."; false; }
      - run:
          name: Run javafmt checks
          command: |
            sbt javafmtCheckAll || \
              { echo "[error] Code not formatted prior to commit. Run 'sbt javafmtAll' then commit the reformatted code."; false; }
      - run:
          name: Run header checks
          command: |
            sbt headerCheckAll || \
              { echo "[error] Code missing headers prior to commit. Run 'sbt headerCreateAll' then commit the updated code."; false; }
      - save_deps_cache

  check-sample-sdk-versions:
    machine:
      image: ubuntu-2004:202201-02
    description: "Check all samples have the same SDK version"
    steps:
      - checkout-and-merge-to-main
      - run:
          name: Scala Samples
          command: |
            if [ $(find ./samples -name plugins.sbt | xargs grep -h "kalix-sdk.version" | uniq | wc -l) -ne 1 ]; then
              echo "Not all Scala samples have the same SDK version:"
              find ./samples -name plugins.sbt | xargs grep "kalix-sdk.version"
              false
            fi
      - run:
          name: Java Samples
          command: |
            if [ $(find ./samples -name pom.xml | xargs grep -h "<kalix-sdk.version>" | tr -s [:space:] | uniq | wc -l) -ne 1 ]; then
              echo "Not all Java samples have the same SDK version:"
              find ./samples -name pom.xml | xargs grep "<kalix-sdk.version>"
              false
            fi
      - run:
          name: Protoc version
          command: |
            # tail 2 + head 1 because CircleCI adds an extra line
            AKKA_GRPC_PROTOC=$(sbt "print coreSdk/protocVersion" 2>/dev/null | tail -n 2 | head -n 1)
            POM_PROTOC_VERSIONS=$(find ./samples ./maven-java/ -name pom.xml | xargs egrep -h "com.google.protobuf:protoc:" | sed 's/.*:protoc://' | sed 's/:exe.*//' | sort | uniq)
            if [ $(echo "$POM_PROTOC_VERSIONS" | wc -l) -ne 1 ]; then
              echo  "Not all Java Samples an Archetypes have the same protoc version:"
              find ./samples ./maven-java/ -name pom.xml | xargs egrep "com.google.protobuf:protoc:"
              false
            elif [ "$AKKA_GRPC_PROTOC" != "$POM_PROTOC_VERSIONS" ]; then
              echo  "Java Samples and Archetypes ($POM_PROTOC_VERSIONS) does not have the same protoc version as Akka gRPC ($AKKA_GRPC_PROTOC)"
              false
            fi

  validate-docs:
    machine:
      image: ubuntu-2004:202201-02
    description: "Validate docs"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
          name: Validate docs
          command: |
            make -C docs
      - save_deps_cache

  validate-doc-links:
    machine:
      image: ubuntu-2004:202201-02
    description: "Validate doc links"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
          name: Validate links
          command: |
            make -C docs validate-links
      - save_deps_cache

  create-pr-sdk-versions-update:
    docker:
      - image: circleci/openjdk:11
    steps:
      - github-cli/setup
      - checkout
      - restore_deps_cache
      - setup_sbt
      - set-sdk-version
      - run:
          name: Create PR to update all sdk versions (samples, sbt and maven)
          command: |
            echo "Updating samples to version $SDK_VERSION"
            ./updateSdkVersions.sh all
            
            BRANCH=bump-sdk-versions-$SDK_VERSION
            git checkout -b $BRANCH
            git config user.name "Kalix Bot"
            git config user.email "kalix.github@lightbend.com"
            git commit . -m "chore: bump SDK versions to $SDK_VERSION"
            git remote add origin-rw https://$GITHUB_TOKEN@github.com/lightbend/kalix-jvm-sdk
            git push --set-upstream origin-rw $BRANCH
            
            gh pr create -B main -t "Auto PR - Bump SDK versions to $SDK_VERSION" -b "This PR should update all existing samples (pom.xml and plugins.sbt) and the maven-java poms. Please review, and merge if okay. [$CIRCLE_SHA1]($CIRCLE_BUILD_URL)" || echo "No changes"; exit 0

  tests:
    docker:
      - image: cimg/openjdk:11.0
    description: "Tests"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
          name: Run tests
          command: sbt test
      - save_deps_cache

  spring-sdk-integration-tests:
    machine:
      image: ubuntu-2004:202201-02
    description: "Java SDK with Spring -  Integration Test"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
          name: Run tests
          command: sbt javaSdkSpring/IntegrationTest/test
      - save_deps_cache

  scripted-tests:
    docker:
      - image: cimg/openjdk:11.0
    description: "sbt plugin scripted tests"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
          name: Run tests
          # would be nice to just depend on publish-local but that's slow because of maven part
          command: sbt coreSdk/publishLocal javaSdkProtobuf/publishLocal scalaSdkProtobuf/publishLocal javaSdkProtobufTestKit/publishLocal scalaSdkProtobufTestKit/publishLocal scripted
      - save_deps_cache

  tck-tests:
    machine:
      image: ubuntu-2004:202201-02
    description: "TCK tests"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
          name: Run Java TCK tests
          command: sbt javaTck/Test/run
      - run:
          name: Run Scala TCK tests
          command: sbt scalaTck/Test/run
      - save_deps_cache

  # by setting a snapshot version with set-sdk-version we publish the deps so that
  # other jobs can use them by depending on this job in the workflow
  publish-local:
    machine:
      image: ubuntu-2004:202201-02
    description: "Build and publish a local version of the artifacts"
    steps:
      - checkout-and-merge-to-main
      - restore_deps_cache
      - setup_sbt
      - set-sdk-version
      - publish-local
      - save_deps_cache

  compile-example-suite-java:
    machine:
      image: ubuntu-2004:202201-02
    description: "Compile Test Projects from Example Suite (Java)"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
            name: Compile test projects from ExampleSuite (Java)
            command: sbt -Dexample.suite.java.enabled codegenJavaCompilationExampleSuite/compile
      - save_deps_cache

  compile-example-suite-scala:
    machine:
      image: ubuntu-2004:202201-02
    description: "Compile Test Projects from Example Suite (Scala)"
    steps:
      - checkout-and-merge-to-main
      - setup_sbt
      - restore_deps_cache
      - run:
            name: Compile test projects from ExampleSuite (Scala)
            command: sbt -Dexample.suite.scala.enabled codegenScalaCompilationExampleSuite/compile
      - save_deps_cache

  maven-java-tests:
    machine:
      image: ubuntu-2004:202201-02
    description: "Maven Java (plugin and archetype tests)"
    steps:
      - checkout-and-merge-to-main
      - restore_deps_cache
      - setup_sbt
      # note: `copy-from-workspace` requires `publish-local` to be run first as declared in workflow section below
      - copy-from-workspace
      - set-sdk-version
      - run:
          name: Run integration tests for Value Entity Archetype
          command: |
            cd maven-java
            mvn -B archetype:generate -DgroupId=com.example -DartifactId=counter-value-entity -DarchetypeGroupId=io.kalix -DarchetypeArtifactId=kalix-maven-archetype -DarchetypeVersion=$SDK_VERSION
            cd counter-value-entity
            mvn -B compile
      - run:
          name: Run integration tests for Event Sourced Entity Archetype
          command: |
            cd maven-java
            mvn -B archetype:generate  -DgroupId=com.example -DartifactId=counter-event-sourced-entity -DarchetypeGroupId=io.kalix -DarchetypeArtifactId=kalix-maven-archetype-event-sourced-entity -DarchetypeVersion=$SDK_VERSION
            cd counter-event-sourced-entity
            mvn -B compile
      - save_deps_cache

  publish:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_sbt
      - restore_deps_cache
      - run: sbt ci-release
      - save_deps_cache

  publish-maven:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_deps_cache
      - setup_sbt
      - set-sdk-version
      - run:
          name: publish m2
          command: sbt publishM2
      - run:
          name: Publish maven plugin and archetype
          command: |
            cd maven-java
            echo $PGP_SECRET | base64 -d | gpg --import --batch
            mkdir -p ~/.m2
            cat >~/.m2/settings.xml \<<EOF;
            <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
            <servers>
              <server>
                <id>ossrh</id>
                <username>$SONATYPE_USERNAME</username>
                <password>$SONATYPE_PASSWORD</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>ossrh</id>
                <activation>
                  <activeByDefault>true</activeByDefault>
                </activation>
                <properties>
                  <gpg.passphrase>$PGP_PASSPHRASE</gpg.passphrase>
                </properties>
              </profile>
            </profiles>
            </settings>
            EOF
            mvn -B versions:set -DnewVersion=$SDK_VERSION
            mvn -P release -B deploy

  publish-tck:
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - setup_remote_docker
      - setup_sbt
      - restore_deps_cache
      - run: bin/docker-login-public-gcr.sh
      - run: sbt javaTck/Docker/publish
      - run: sbt scalaTck/Docker/publish
      - save_deps_cache

  publish-docs:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - setup_sbt
      - restore_deps_cache
      # deploy key for pushing docs to branch
      - add_ssh_keys:
          fingerprints:
            - "92:20:53:ff:db:d1:3f:f3:79:85:53:b5:9e:4b:b4:b4"
      - run:
          name: Publish docs
          command: make -C docs deploy
      - save_deps_cache

workflows:
  CI:
    jobs:
      - checks
      - publish-local
      - check-sample-sdk-versions

      - validate-docs:
          requires:
            - checks
      - validate-doc-links:
          requires:
            - checks
      - tests:
          requires:
            - checks
      - scripted-tests:
          requires:
            - checks

      - tck-tests:
          requires:
            - checks

      - compile-example-suite-java:
          requires:
            - checks

      - compile-example-suite-scala:
          requires:
            - checks

      - maven-java-tests:
          requires:
            - checks
            - publish-local
      - spring-sdk-integration-tests:
          requires:
            - checks

      - publish:
          filters: # version tags only
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      - publish-maven:
          filters: # version tags only
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - publish

      - publish-tck:
          filters: # version tags only
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - publish

      - publish-docs:
          filters: # version tags only (but no snapshots/milestones)
            tags:
              only: /^v\d+(\.\d+){1,2}$/
            branches:
              ignore: /.*/
          requires:
            # we only publish the docs if all publishing jobs are successful, otherwise we have a 'broken' release
            - publish
            - publish-maven
            - publish-tck

      - create-pr-sdk-versions-update:
          filters: # version tags only (but no snapshots/milestones)
            tags:
              only: /^v\d+(\.\d+){1,2}$/
            branches:
              ignore: /.*/
          requires:
            # we only create the versions bump PR after publish-docs is successful, which means release was successful
            - publish-docs
