version: "3"
services:
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.11
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dconfig.resource=dev-mode.conf
        -Dlogback.configurationFile=logback-dev-mode.xml
        -Dkalix.proxy.eventing.support=google-pubsub-emulator
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: ${USER_FUNCTION_PORT:-8080}
      PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
    depends_on:
      gcloud-pubsub-emulator:
        condition: service_healthy

  gcloud-pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:432.0.0-emulators
    command: gcloud beta emulators pubsub start --project=test --host-port=0.0.0.0:8085
    ports:
      - 8085:8085
    healthcheck:
      test: curl http://0.0.0.0:8085/v1/projects/test/topics || exit -1
      interval: 5s
      timeout: 5s
      retries: 10
