#tag::customer-registry-subscriber[]
version: "3"
services:
#end::customer-registry-subscriber[]
  # note the ports being different from other sample docker-compose files to allow this service to run
  # on the same local machine as the java-protobuf-eventsourced-customer-registry
#tag::customer-registry-subscriber[]  
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.26
    container_name: java-protobuf-eventsourced-customer-registry-subscriber
    ports:
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dkalix.dev-mode.service-port-mappings.customer-registry=host.docker.internal:9000
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: "8081"
#end::customer-registry-subscriber[]