# note the ports being different from other sample docker-compose files to allow this service to run
# on the same local machine as the java-spring-eventsourced-customer-registry
#tag::customer-registry-subscriber[]
version: "3"
services:
  kalix-proxy:
    image: gcr.io/kalix-public/kalix-proxy:1.1.23
    container_name: java-spring-eventsourced-customer-registry-subscriber
    ports:
      - "9001:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dconfig.resource=dev-mode.conf
        -Dlogback.configurationFile=logback-dev-mode.xml
        -Dkalix.dev-mode.service-port-mappings.customer-registry=host.docker.internal:9000
      USER_FUNCTION_HOST: ${USER_FUNCTION_HOST:-host.docker.internal}
      USER_FUNCTION_PORT: "8081"
#end::customer-registry-subscriber[]