# note the ports being different from other sample docker-compose files to allow this service to run
# on the same local machine as the java-spring-eventsourced-customer-registry
#tag::customer-registry-subscriber[]
version: "3"
services:
  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.1.32
    container_name: java-spring-eventsourced-customer-registry-subscriber
    ports:
      - "9001:9001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      HTTP_PORT: "9001"
      JAVA_TOOL_OPTIONS: >
        -Dkalix.dev-mode.service-port-mappings.customer-registry=host.docker.internal:9000
      USER_SERVICE_HOST: ${USER_SERVICE_HOST:-host.docker.internal}
      USER_SERVICE_PORT: "8081"
#end::customer-registry-subscriber[]
