# tag::persistence-mode[]
version: "3"
services:
  kalix-runtime:
    image: gcr.io/kalix-public/kalix-runtime:1.1.32
    # uncomment volumes when persistence is enabled
    volumes: # <1>
      - ./target/kalix:/var/kalix
    ports:
      - "9000:9000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PERSISTENCE_ENABLED: "true" # <2>
      # end::persistence-mode[]
      JAVA_TOOL_OPTIONS: >
        -Dkalix.proxy.eventing.support=google-pubsub-emulator
      # tag::persistence-mode[]
      USER_SERVICE_HOST: ${USER_SERVICE_HOST:-host.docker.internal}
      USER_SERVICE_PORT: ${USER_SERVICE_PORT:-8080}
      # end::persistence-mode[]
      # Comment to enable ACL check in dev-mode (see https://docs.kalix.io/java-protobuf/access-control.html#_local_development_with_acls)
      ACL_ENABLED: "false"
      # Uncomment to enable advanced view features locally (note: disabled in deployed services by default)
      #VIEW_FEATURES_ALL: "true"
      # Uncomment to disable the JWT dev secret
      #JWT_DEV_SECRET: "false"
      # Uncomment to set the JWT dev secret issuer
      #JWT_DEV_SECRET_ISSUER: "my-issuer"
      # Uncomment if using pubsub emulator
      PUBSUB_EMULATOR_HOST: gcloud-pubsub-emulator
  gcloud-pubsub-emulator:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:341.0.0
    command: gcloud beta emulators pubsub start --project=test --host-port=0.0.0.0:8085
    ports:
      - 8085:8085
