name: Publish

on:
  push:
    branches:
      - main
      - release-*
    tags: ["v*"]

permissions:
  contents: read

jobs:
  publish:
    name: Publish (sbt & Maven)
    runs-on: ubuntu-22.04
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.5
        uses: coursier/cache-action@1ff273bff02a8787bc9f1877d347948af647956d

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.17.0.5

      - name: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        run: sbt --client ci-release

      - name: sbt publishM2
        run: sbt --client publishM2

      - name: mvn deploy
        run: ./.github/publish-maven.sh
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PUBLISH_USER: ${{ secrets.PUBLISH_USER }}
          PUBLISH_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

  publish-documentation:
    name: Documentation
    runs-on: ubuntu-22.04
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.5
        uses: coursier/setup-action@7bde40eee928896f074dbb76d22dd772eed5c65f
        with:
          jvm: temurin:1.17.0.5

      - name: Publish docs
        run: make -C docs deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
