name: Samples

on:
  pull_request:
  push:
    branches:
      - main
    tags-ignore:
      - v*

permissions:
  contents: read

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: samples-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-local:
    name: Build and publish artifacts and plugins locally for other tests to use
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        # v3.1.0
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.0
        uses: coursier/setup-action@70323223454ac2a9eb2de46f389b4d045cbcdea5
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.3
        uses: coursier/cache-action@566e01fea33492e5a89706b43fb0d3fc884154f9

      - name: Cache Maven repository
        # https://github.com/actions/cache/releases
        # v3.3.1
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('maven-java/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build and publish artifacts and plugins
        id: build_sdk
        run: |-
          git status
          sbt -Ddisable.apidocs=true publishM2 publishLocal
          # the SDK_VERSION is later used to run the maven tests (see below)
          sbt "print javaSdkProtobuf/version" > version.txt
          echo "== Extracting from sbt build (start) =="
          cat version.txt
          echo "== Extracting from sbt build (end) =="
          SDK_VERSION='$(cat version.txt | tail -n 2 | head -n 1)
          echo "== using Kalix JVM SDK version: '${SDK_VERSION}'"
          echo $SDK_VERSION > ~/kalix-sdk-version.txt
          echo 'sdk_version='${SDK_VERSION} >> $GITHUB_OUTPUT

      - name: Build maven-java
        env:
          SDK_VERSION: ${{ steps.build_sdk.outputs.sdk_version }}
        run: |-
          cd maven-java
          echo "Running maven-java with SDK version: '${SDK_VERSION}'"
          mvn versions:set -DnewVersion=${SDK_VERSION}
          mvn verify install

      - name: Package io.kalix
        run: |-
          cd
          tar -czf dependencies.tar.gz .m2/repository/io/kalix/ .ivy2/local/io.kalix/ kalix-sdk-version.txt

      - name: Upload
        # https://github.com/actions/upload-artifact/releases
        # v3.1.2
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: m2-cache
          path: ~/dependencies.tar.gz
          if-no-files-found: error
          retention-days: 1

  all-samples-tested:
    name: Ensure all sample projects are listed
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        # v3.1.0
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - run: .github/ci-check-samples.sh

  maven-samples:
    name: Maven samples
    needs: publish-local
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sample: java-protobuf-shopping-cart-quickstart, it: true }
          - { sample: java-protobuf-customer-registry-quickstart, it: true }
          - { sample: java-protobuf-customer-registry-kafka-quickstart, it: true }
          - { sample: java-protobuf-customer-registry-views-quickstart, it: true }

          - { sample: java-spring-shopping-cart-quickstart, it: true }
          - { sample: java-spring-customer-registry-quickstart, it: true }
          - { sample: java-spring-customer-registry-views-quickstart, it: true }

          - { sample: java-protobuf-fibonacci-action, it: false }
          - { sample: java-protobuf-doc-snippets, it: false }
          - { sample: java-protobuf-first-service, it: false }
          - { sample: java-protobuf-valueentity-customer-registry, it: false }
          - { sample: java-protobuf-view-store, it: true }

          - { sample: java-spring-fibonacci-action, it: true }
          - { sample: java-spring-doc-snippets, it: false }
          - { sample: java-spring-view-store, it: true }

          - { sample: java-protobuf-eventsourced-customer-registry, it: true }
          - { sample: java-protobuf-eventsourced-customer-registry-subscriber, it: false }
          - { sample: java-protobuf-eventsourced-counter, pre_cmd: 'docker-compose -f ../../.circleci/google-pubsub-emulator-docker-compose.yml up -d', it: true }
          - { sample: java-protobuf-eventsourced-shopping-cart, it: true }

          - { sample: java-spring-eventsourced-customer-registry, it: true }
          # FIXME would be good to enable integration tests but currently failing to resolve host.docker.internal
          # pre_cmd: 'docker-compose -f ../java-spring-eventsourced-customer-registry/docker-compose.yml up -d; (cd ../java-spring-eventsourced-customer-registry/; mvn spring-boot:run &);sleep 10;'
          - { sample: java-spring-eventsourced-customer-registry-subscriber, it: false }
          - { sample: java-spring-eventsourced-shopping-cart, it: true }

          - { sample: java-protobuf-valueentity-counter, it: true }
          - { sample: java-protobuf-valueentity-counter-spring-client, verify: true, it: false }
          - { sample: java-protobuf-valueentity-shopping-cart, it: true }

          - { sample: java-spring-valueentity-counter, it: true }
          - { sample: java-spring-valueentity-shopping-cart, it: true }
          - { sample: java-spring-valueentity-customer-registry, it: true }

          # FIXME add eventing integration tests (related to https://github.com/lightbend/kalix/issues/7811)
          - { sample: java-spring-eventsourced-counter, pre_cmd: 'docker-compose -f ../../.circleci/google-pubsub-emulator-docker-compose.yml up -d', it: true }

          - { sample: java-protobuf-replicatedentity-shopping-cart, it: true }
          - { sample: java-protobuf-replicatedentity-examples, it: true }

          - { sample: java-protobuf-reliable-timers, it: false }
          - { sample: java-spring-reliable-timers, it: true }

          - { sample: java-spring-transfer-workflow, it: true }
          - { sample: java-spring-transfer-workflow-compensation, it: true }

    steps:
      - name: Checkout
        # v3.1.0
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.0
        uses: coursier/setup-action@70323223454ac2a9eb2de46f389b4d045cbcdea5
        with:
          jvm: temurin:1.17

      - name: Cache Maven repository
        # https://github.com/actions/cache/releases
        # v3.3.1
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('maven-java/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Download pre-built cache
        # https://github.com/actions/download-artifact/releases
        # v3.0.2
        uses: actions/download-artifact@d2278a10efbd646909370fd49fb454cb04e368e3
        with:
          name: m2-cache
          path: ~/

      - name: Unpack
        run: |-
          cd
          tar -xf dependencies.tar.gz

      - name: ${{ matrix.sample }} test-compile
        env:
          DIR: ${{ matrix.sample }}
        run: |-
          export SDK_VERSION=$(cat ~/kalix-sdk-version.txt)
          cd samples/${DIR}
          echo "Running mvn on ${DIR} with SDK version: '${SDK_VERSION}'"
          # must also compile without the profile!
          mvn -Dkalix-sdk.version=${SDK_VERSION} test-compile

      - name: ${{ matrix.sample }} verify
        if: matrix.verify || matrix.it
        env:
          DIR: ${{ matrix.sample }}
          PRE_CMD: ${{ matrix.pre_cmd }}
        run: |-
          export SDK_VERSION=$(cat ~/kalix-sdk-version.txt)
          cd samples/${DIR}
          if [ true == '${{matrix.verify}}' ]; then
            mvn -Dkalix-sdk.version=${SDK_VERSION} verify
          fi
          if [ true == '${{matrix.it}}' ]; then
            ${PRE_CMD}
            mvn -Dkalix-sdk.version=${SDK_VERSION} verify -Pit
          fi

      - name: ${{ matrix.sample }} rm & test-compile
        env:
          DIR: ${{ matrix.sample }}
        run: |-
          export SDK_VERSION=$(cat ~/kalix-sdk-version.txt)
          cd samples/${DIR}
          echo "==== Verifying that generated unmanaged sources compile ===="
          rm -rf src/main/java src/test/java src/it/java
          mvn -Dkalix-sdk.version=${SDK_VERSION} test-compile

  sbt-samples:
    name: sbt
    needs: publish-local
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - { sample: scala-protobuf-customer-registry-quickstart, test: true }

          - { sample: scala-protobuf-fibonacci-action, test: true }
          - { sample: scala-protobuf-first-service, test: false }
          - { sample: scala-protobuf-doc-snippets, test: true }
          - { sample: scala-protobuf-valueentity-customer-registry, test: true }
          - { sample: scala-protobuf-view-store, test: true }

          - { sample: scala-protobuf-eventsourced-customer-registry, test: true }
          - { sample: scala-protobuf-eventsourced-customer-registry-subscriber, test: true }
          - { sample: scala-protobuf-eventsourced-counter, pre_test: 'docker-compose -f ../../.circleci/google-pubsub-emulator-docker-compose.yml up -d', test: true }
          - { sample: scala-protobuf-eventsourced-shopping-cart, test: true }

          - { sample: scala-protobuf-valueentity-counter, test: true }
          - { sample: scala-protobuf-valueentity-shopping-cart, test: true }

          - { sample: scala-protobuf-replicatedentity-shopping-cart, test: true }
          - { sample: scala-protobuf-replicatedentity-examples, test: true }

          - { sample: scala-protobuf-reliable-timers, test: true }

    steps:
      - name: Checkout
        # v3.1.0
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Set up JDK 17
        # https://github.com/coursier/setup-action/releases
        # v1.3.0
        uses: coursier/setup-action@70323223454ac2a9eb2de46f389b4d045cbcdea5
        with:
          jvm: temurin:1.17

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        # v6.4.3
        uses: coursier/cache-action@566e01fea33492e5a89706b43fb0d3fc884154f9

      - name: Download pre-built cache
        # https://github.com/actions/download-artifact/releases
        # v3.0.2
        uses: actions/download-artifact@d2278a10efbd646909370fd49fb454cb04e368e3
        with:
          name: m2-cache
          path: ~/

      - name: Unpack
        run: |-
          cd
          tar -xf dependencies.tar.gz

      - name: sbt Test/compile
        env:
          DIR: ${{ matrix.sample }}
        run: |-
          export SDK_VERSION=$(cat ~/kalix-sdk-version.txt)
          cd samples/${DIR}
          echo "Running sbt on ${DIR} with SDK version: '$SDK_VERSION'"
          sbt --client -Dkalix-sdk.version=$SDK_VERSION Test/compile

      - name: sbt test
        if: matrix.test
        env:
          DIR: ${{ matrix.sample }}
          PRE_TEST_CMD: ${{ matrix.pre_test }}
        run: |-
          export SDK_VERSION=$(cat ~/kalix-sdk-version.txt)
          cd samples/${DIR}
          ${PRE_TEST_CMD}
          sbt  --client -Dkalix-sdk.version=$SDK_VERSION test

      - name: rm & sbt Test/compile
        env:
          DIR: ${{ matrix.sample }}
        run: |-
          export SDK_VERSION=$(cat ~/kalix-sdk-version.txt)
          cd samples/${DIR}
          echo "==== Verifying that generated unmanaged sources compile ===="
          rm -rf src/main/scala src/test/scala src/it/scala
          sbt  --client -Dkalix-sdk.version=$SDK_VERSION Test/compile
